version: "3.9"

services:
  user_manager:
    build:
      context: ../../
      dockerfile: adapters/userManager/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ../../core:/var/www/html/core
      - ../../adapters/userManager/public:/var/www/html
    env_file:
      - ../../infrastructure/.env
  control_room:
    build:
      context: ../../
      dockerfile: adapters/controlRoom/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../../core:/var/www/html/core
      - ../../adapters/controlRoom/public:/var/www/html
    env_file:
      - ../../infrastructure/.env