version: "3.9"

services:
  user_manager:
    build:
      context: ../../
      dockerfile: adapters/userManager/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ../../core:/var/www/html/core
      - ../../adapters/userManager/public:/var/www/html
    env_file:
      - ../../infrastructure/.env
    depends_on:
      - mysql
  control_room:
    build:
      context: ../../
      dockerfile: adapters/controlRoom/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../../core:/var/www/html/core
      - ../../adapters/controlRoom/public:/var/www/html
    env_file:
      - ../../infrastructure/.env
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: